/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui.panel;

/**
 *
 * @author immsf
 */
public class CreatePayslip extends javax.swing.JPanel {

    /**
     * Creates new form CreatePayslip
     */
    public CreatePayslip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStaffId1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStaffId2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStaffId3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStaffId4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        calDateOfBirth = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        calDateOfBirth1 = new com.toedter.calendar.JDateChooser();
        txtStaffId5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtStaffId6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtStaffId7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtStaffId8 = new javax.swing.JTextField();
        cmbDesignation = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(580, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(580, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Staff Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        jPanel2.setBackground(new java.awt.Color(128, 3, 67));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GENERATE");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 100, 40));

        jPanel3.setBackground(new java.awt.Color(128, 3, 67));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESET");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 100, 40));

        jPanel5.setBackground(new java.awt.Color(64, 0, 33));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CREATE EMPLOYEE PAYSLIP");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        txtStaffId1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtStaffId1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStaffId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffId1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStaffId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Basic Salary");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 30));

        txtStaffId2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtStaffId2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStaffId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffId2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStaffId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Allowance");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 30));

        txtStaffId3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtStaffId3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStaffId3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffId3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStaffId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 220, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Bonus");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 30));

        txtStaffId4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtStaffId4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStaffId4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffId4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStaffId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 220, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Date From");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 30));

        calDateOfBirth.setBackground(new java.awt.Color(255, 255, 255));
        calDateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(calDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 220, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Date To");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, 30));

        calDateOfBirth1.setBackground(new java.awt.Color(255, 255, 255));
        calDateOfBirth1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(calDateOfBirth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 220, 30));

        txtStaffId5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtStaffId5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStaffId5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffId5ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStaffId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 220, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("Leaves Taken");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 100, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Deduction");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 30));

        txtStaffId6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtStaffId6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStaffId6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffId6ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStaffId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 220, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setText("Gross Salary");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 30));

        txtStaffId7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtStaffId7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStaffId7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffId7ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStaffId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 220, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Net Salary");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, 30));

        txtStaffId8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtStaffId8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStaffId8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffId8ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStaffId8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 220, 30));

        cmbDesignation.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Item 2", "Item 3", "Item 4" }));
        cmbDesignation.setBorder(null);
        jPanel1.add(cmbDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void txtStaffId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffId1ActionPerformed

    private void txtStaffId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffId2ActionPerformed

    private void txtStaffId3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffId3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffId3ActionPerformed

    private void txtStaffId4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffId4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffId4ActionPerformed

    private void txtStaffId5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffId5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffId5ActionPerformed

    private void txtStaffId6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffId6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffId6ActionPerformed

    private void txtStaffId7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffId7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffId7ActionPerformed

    private void txtStaffId8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffId8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffId8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calDateOfBirth;
    private com.toedter.calendar.JDateChooser calDateOfBirth1;
    private javax.swing.JComboBox<String> cmbDesignation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtStaffId1;
    private javax.swing.JTextField txtStaffId2;
    private javax.swing.JTextField txtStaffId3;
    private javax.swing.JTextField txtStaffId4;
    private javax.swing.JTextField txtStaffId5;
    private javax.swing.JTextField txtStaffId6;
    private javax.swing.JTextField txtStaffId7;
    private javax.swing.JTextField txtStaffId8;
    // End of variables declaration//GEN-END:variables
}
