/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui.panel;

import com.sliit.itp.service.Attendance;
import com.sliit.itp.service.Leave;

/**
 *
 * @author user
 */
public class MarkAttendance extends javax.swing.JPanel {

    /**
     * Creates new form MarkAttendance
     */
    Attendance attendance = new Attendance();
    public MarkAttendance() {
        initComponents();
        lblCurrentDateTime.setText(String.valueOf(attendance.getCurrentDateTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMarkAttendance = new javax.swing.JPanel();
        pnlMarkAttendanceTitle = new javax.swing.JPanel();
        lblAttendanceTitle = new javax.swing.JLabel();
        pnlAttendanceMarking = new javax.swing.JPanel();
        lblEmpIdGet = new javax.swing.JLabel();
        lblDateTimeGet = new javax.swing.JLabel();
        lblCurrentDateTime = new javax.swing.JLabel();
        lblEmpId1 = new javax.swing.JLabel();
        lblDateTime1 = new javax.swing.JLabel();
        lblInOut = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(580, 600));
        setMinimumSize(new java.awt.Dimension(580, 600));
        setPreferredSize(new java.awt.Dimension(580, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMarkAttendance.setBackground(new java.awt.Color(255, 255, 255));
        pnlMarkAttendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMarkAttendanceTitle.setBackground(new java.awt.Color(0, 51, 0));
        pnlMarkAttendanceTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAttendanceTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAttendanceTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendanceTitle.setText("MARK ATTENDANCE");
        pnlMarkAttendanceTitle.add(lblAttendanceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, 30));

        pnlMarkAttendance.add(pnlMarkAttendanceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 50));

        pnlAttendanceMarking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmpIdGet.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblEmpIdGet.setText("EMPLOYEE ID:");
        pnlAttendanceMarking.add(lblEmpIdGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        lblDateTimeGet.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDateTimeGet.setText("DATE/TIME:");
        pnlAttendanceMarking.add(lblDateTimeGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        lblCurrentDateTime.setText("Date:Time");
        pnlAttendanceMarking.add(lblCurrentDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 374, 210, 30));

        lblEmpId1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblEmpId1.setText("EMPLOYEE ID:");
        pnlAttendanceMarking.add(lblEmpId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        lblDateTime1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDateTime1.setText("DATE/TIME:");
        pnlAttendanceMarking.add(lblDateTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 70, -1));

        lblInOut.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblInOut.setText("In/out");
        pnlAttendanceMarking.add(lblInOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 30));

        pnlMarkAttendance.add(pnlAttendanceMarking, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 450, 420));

        add(pnlMarkAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAttendanceTitle;
    private javax.swing.JLabel lblCurrentDateTime;
    private javax.swing.JLabel lblDateTime1;
    private javax.swing.JLabel lblDateTimeGet;
    private javax.swing.JLabel lblEmpId1;
    private javax.swing.JLabel lblEmpIdGet;
    private javax.swing.JLabel lblInOut;
    private javax.swing.JPanel pnlAttendanceMarking;
    private javax.swing.JPanel pnlMarkAttendance;
    private javax.swing.JPanel pnlMarkAttendanceTitle;
    // End of variables declaration//GEN-END:variables
}
