/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui.panel;

/**
 *
 * @author immsf
 */
public class PaymentReport extends javax.swing.JPanel {

    /**
     * Creates new form PaymentReport
     */
    public PaymentReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbDesignation = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        calDateOfBirth = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        calDateOfBirth1 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        calDateOfBirth2 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        calDateOfBirth3 = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(580, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(580, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(580, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Employee ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        jPanel1.setBackground(new java.awt.Color(128, 3, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BY PERIOD");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, -1, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 140, 40));

        jPanel3.setBackground(new java.awt.Color(128, 3, 67));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESET");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 70, 40));

        jPanel5.setBackground(new java.awt.Color(64, 0, 33));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GENERATE SALARY REPORTS");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 50));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 70));

        cmbDesignation.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Item 2", "Item 3", "Item 4" }));
        cmbDesignation.setBorder(null);
        jPanel2.add(cmbDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Date From");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, 30));

        calDateOfBirth.setBackground(new java.awt.Color(255, 255, 255));
        calDateOfBirth.setDateFormatString("dd-MM-yyyy");
        calDateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(calDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 220, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Date To");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 30));

        calDateOfBirth1.setBackground(new java.awt.Color(255, 255, 255));
        calDateOfBirth1.setDateFormatString("dd-MM-yyyy");
        calDateOfBirth1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(calDateOfBirth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 220, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 590, -1));

        jPanel4.setBackground(new java.awt.Color(128, 3, 67));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BY STAFF MEMBER");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, -1, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("Date From");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        calDateOfBirth2.setBackground(new java.awt.Color(255, 255, 255));
        calDateOfBirth2.setDateFormatString("dd-MM-yyyy");
        calDateOfBirth2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(calDateOfBirth2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Date To");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 30));

        calDateOfBirth3.setBackground(new java.awt.Color(255, 255, 255));
        calDateOfBirth3.setDateFormatString("dd-MM-yyyy");
        calDateOfBirth3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(calDateOfBirth3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, 30));

        jPanel6.setBackground(new java.awt.Color(128, 3, 67));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RESET");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 70, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calDateOfBirth;
    private com.toedter.calendar.JDateChooser calDateOfBirth1;
    private com.toedter.calendar.JDateChooser calDateOfBirth2;
    private com.toedter.calendar.JDateChooser calDateOfBirth3;
    private javax.swing.JComboBox<String> cmbDesignation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
