/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui.panel;

/**
 *
 * @author user
 */
public class ViewAttendance extends javax.swing.JPanel {

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAttendanceView = new javax.swing.JPanel();
        pnlAttendanceSummary = new javax.swing.JPanel();
        lblEmpId = new javax.swing.JLabel();
        cmbAttendanceStaff = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        dateAttendanceFrom = new com.toedter.calendar.JDateChooser();
        lblDate = new javax.swing.JLabel();
        dateAttendanceReqDate = new com.toedter.calendar.JDateChooser();
        dateAttendanceTo = new com.toedter.calendar.JDateChooser();
        lblTo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendanceSummary = new javax.swing.JTable();
        btnSearch = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        btnReset = new javax.swing.JPanel();
        lblReset = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAttendanceView.setBackground(new java.awt.Color(255, 255, 255));
        pnlAttendanceView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAttendanceSummary.setBackground(new java.awt.Color(255, 255, 255));
        pnlAttendanceSummary.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmpId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblEmpId.setText("Staff Id");
        pnlAttendanceSummary.add(lblEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 29, -1, 30));

        cmbAttendanceStaff.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbAttendanceStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "EMP0001" }));
        cmbAttendanceStaff.setMaximumSize(new java.awt.Dimension(95, 24));
        cmbAttendanceStaff.setMinimumSize(new java.awt.Dimension(95, 24));
        pnlAttendanceSummary.add(cmbAttendanceStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 190, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("SEARCH");
        pnlAttendanceSummary.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        lblFrom.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblFrom.setText("From");
        pnlAttendanceSummary.add(lblFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 69, -1, 30));

        dateAttendanceFrom.setDateFormatString("dd-MM-yyyy");
        dateAttendanceFrom.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dateAttendanceFrom.setMaximumSize(new java.awt.Dimension(95, 24));
        dateAttendanceFrom.setMinimumSize(new java.awt.Dimension(95, 24));
        pnlAttendanceSummary.add(dateAttendanceFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 190, 30));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblDate.setText("Date");
        pnlAttendanceSummary.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 34, -1, 30));

        dateAttendanceReqDate.setDateFormatString("dd-MM-yyyy");
        dateAttendanceReqDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dateAttendanceReqDate.setMaximumSize(new java.awt.Dimension(95, 24));
        dateAttendanceReqDate.setMinimumSize(new java.awt.Dimension(95, 24));
        pnlAttendanceSummary.add(dateAttendanceReqDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 34, 190, 30));

        dateAttendanceTo.setDateFormatString("dd-MM-yyyy");
        dateAttendanceTo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dateAttendanceTo.setMaximumSize(new java.awt.Dimension(95, 24));
        dateAttendanceTo.setMinimumSize(new java.awt.Dimension(95, 24));
        pnlAttendanceSummary.add(dateAttendanceTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 190, 30));

        lblTo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTo.setText("To");
        pnlAttendanceSummary.add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 69, 30, 30));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 80));

        tblAttendanceSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "EMPLOYEE ID", "DATE", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(tblAttendanceSummary);

        pnlAttendanceSummary.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 540, 120));

        btnSearch.setBackground(new java.awt.Color(128, 3, 67));
        btnSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setText("SEARCH");
        btnSearch.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 12, -1, -1));

        pnlAttendanceSummary.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 100, 40));

        btnReset.setBackground(new java.awt.Color(128, 3, 67));
        btnReset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReset.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblReset.setForeground(new java.awt.Color(255, 255, 255));
        lblReset.setText("RESET");
        btnReset.add(lblReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 12, -1, -1));

        pnlAttendanceSummary.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 100, 40));

        pnlAttendanceView.add(pnlAttendanceSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 580, 530));

        jPanel1.setBackground(new java.awt.Color(64, 0, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ATTENDANCE SUMMARY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 50));

        pnlAttendanceView.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 70));

        add(pnlAttendanceView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnReset;
    private javax.swing.JPanel btnSearch;
    private javax.swing.JComboBox<String> cmbAttendanceStaff;
    private com.toedter.calendar.JDateChooser dateAttendanceFrom;
    private com.toedter.calendar.JDateChooser dateAttendanceReqDate;
    private com.toedter.calendar.JDateChooser dateAttendanceTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel pnlAttendanceSummary;
    private javax.swing.JPanel pnlAttendanceView;
    private javax.swing.JTable tblAttendanceSummary;
    // End of variables declaration//GEN-END:variables
}
