/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui;

import com.sliit.itp.staff.ui.panel.MarkAttendance;
import com.sliit.itp.staff.ui.panel.ViewAttendance;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author user
 */
public class AttendanceManagement extends javax.swing.JFrame {

    GridBagLayout gridBaglayout = new GridBagLayout();
    MarkAttendance markAttendance;
    ViewAttendance viewAttendance;

    /**
     * Creates new form AttendanceManagement
     */
    public AttendanceManagement() {
        initComponents();
        markAttendance = new MarkAttendance();
        viewAttendance = new ViewAttendance();
        pnlDynamic.setLayout(gridBaglayout);

        GridBagConstraints constraints = new GridBagConstraints();

        constraints.gridx = 0;
        constraints.gridy = 0;
        pnlDynamic.add(markAttendance, constraints);

        constraints.gridx = 0;
        constraints.gridy = 0;
        pnlDynamic.add(viewAttendance, constraints);

        markAttendance.setVisible(true);
        viewAttendance.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAttendanceBase = new javax.swing.JPanel();
        pnlAttendanceNav = new javax.swing.JPanel();
        lblAttendanceTitle = new javax.swing.JLabel();
        btnViewAttendance = new javax.swing.JPanel();
        lblMarkAttendance = new javax.swing.JLabel();
        btnMarkAttendance1 = new javax.swing.JPanel();
        lblMarkAttendance1 = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlDynamic = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAttendanceBase.setBackground(new java.awt.Color(255, 255, 255));
        pnlAttendanceBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAttendanceNav.setBackground(new java.awt.Color(99, 0, 50));
        pnlAttendanceNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAttendanceTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblAttendanceTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblAttendanceTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendanceTitle.setText("ATTENDANCE ");
        pnlAttendanceNav.add(lblAttendanceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 30));

        btnViewAttendance.setBackground(new java.awt.Color(64, 0, 33));
        btnViewAttendance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnViewAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAttendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAttendanceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewAttendanceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewAttendanceMouseReleased(evt);
            }
        });
        btnViewAttendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMarkAttendance.setBackground(new java.awt.Color(0, 97, 17));
        lblMarkAttendance.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblMarkAttendance.setForeground(new java.awt.Color(255, 255, 255));
        lblMarkAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-data-sheet-20.png"))); // NOI18N
        lblMarkAttendance.setText("Attendance Summary");
        btnViewAttendance.add(lblMarkAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        pnlAttendanceNav.add(btnViewAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 41));

        btnMarkAttendance1.setBackground(new java.awt.Color(64, 0, 33));
        btnMarkAttendance1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMarkAttendance1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMarkAttendance1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMarkAttendance1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMarkAttendance1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMarkAttendance1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMarkAttendance1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMarkAttendance1MouseReleased(evt);
            }
        });
        btnMarkAttendance1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMarkAttendance1.setBackground(new java.awt.Color(0, 97, 17));
        lblMarkAttendance1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblMarkAttendance1.setForeground(new java.awt.Color(255, 255, 255));
        lblMarkAttendance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-attendance-20.png"))); // NOI18N
        lblMarkAttendance1.setText("Mark Attendance");
        btnMarkAttendance1.add(lblMarkAttendance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 40));

        pnlAttendanceNav.add(btnMarkAttendance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 41));

        pnlExit.setBackground(new java.awt.Color(64, 0, 33));
        pnlExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExit.setPreferredSize(new java.awt.Dimension(220, 41));
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExitMouseReleased(evt);
            }
        });
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-exit-20.png"))); // NOI18N
        jLabel5.setText("Exit Module");
        jLabel5.setFocusable(false);
        pnlExit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 41));

        pnlAttendanceNav.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 220, 40));

        pnlAttendanceBase.add(pnlAttendanceNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        pnlDynamic.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlDynamicLayout = new javax.swing.GroupLayout(pnlDynamic);
        pnlDynamic.setLayout(pnlDynamicLayout);
        pnlDynamicLayout.setHorizontalGroup(
            pnlDynamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        pnlDynamicLayout.setVerticalGroup(
            pnlDynamicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pnlAttendanceBase.add(pnlDynamic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 580, 600));

        getContentPane().add(pnlAttendanceBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarkAttendance1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarkAttendance1MouseClicked
        markAttendance.setVisible(true);
        viewAttendance.setVisible(false);
    }//GEN-LAST:event_btnMarkAttendance1MouseClicked

    private void btnViewAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAttendanceMouseClicked
        markAttendance.setVisible(false);
        viewAttendance.setVisible(true);
    }//GEN-LAST:event_btnViewAttendanceMouseClicked

    private void pnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseClicked
        // TODO add your handling code here:
        StaffManagementHome staffHome = new StaffManagementHome();
        staffHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlExitMouseClicked

    private void btnMarkAttendance1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarkAttendance1MouseEntered
        btnMarkAttendance1.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_btnMarkAttendance1MouseEntered

    private void btnMarkAttendance1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarkAttendance1MouseExited
        btnMarkAttendance1.setBackground(new Color(64, 0, 33));
    }//GEN-LAST:event_btnMarkAttendance1MouseExited

    private void btnMarkAttendance1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarkAttendance1MousePressed
        btnMarkAttendance1.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_btnMarkAttendance1MousePressed

    private void btnMarkAttendance1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarkAttendance1MouseReleased
        btnMarkAttendance1.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_btnMarkAttendance1MouseReleased

    private void btnViewAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAttendanceMouseEntered
        btnViewAttendance.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_btnViewAttendanceMouseEntered

    private void btnViewAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAttendanceMouseExited
        btnViewAttendance.setBackground(new Color(64, 0, 33));
    }//GEN-LAST:event_btnViewAttendanceMouseExited

    private void btnViewAttendanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAttendanceMousePressed
        btnViewAttendance.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_btnViewAttendanceMousePressed

    private void btnViewAttendanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAttendanceMouseReleased
        btnViewAttendance.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_btnViewAttendanceMouseReleased

    private void pnlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseEntered
        pnlExit.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_pnlExitMouseEntered

    private void pnlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseExited
        pnlExit.setBackground(new Color(64, 0, 33));
    }//GEN-LAST:event_pnlExitMouseExited

    private void pnlExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMousePressed
        pnlExit.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_pnlExitMousePressed

    private void pnlExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseReleased
        pnlExit.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_pnlExitMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnMarkAttendance1;
    private javax.swing.JPanel btnViewAttendance;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAttendanceTitle;
    private javax.swing.JLabel lblMarkAttendance;
    private javax.swing.JLabel lblMarkAttendance1;
    private javax.swing.JPanel pnlAttendanceBase;
    private javax.swing.JPanel pnlAttendanceNav;
    private javax.swing.JPanel pnlDynamic;
    private javax.swing.JPanel pnlExit;
    // End of variables declaration//GEN-END:variables
}
