/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui;

import com.sliit.itp.staff.ui.panel.ApplyLeave;
import com.sliit.itp.staff.ui.panel.ApproveLeave;
import com.sliit.itp.staff.ui.panel.LeaveSummary;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author user
 */
public class LeaveManagement extends javax.swing.JFrame {

    GridBagLayout gridBaglayout = new GridBagLayout();
    ApplyLeave applyLeave;
    LeaveSummary leaveSummary;
    ApproveLeave approveLeave;

    /**
     * Creates new form LeaveManagement
     */
    public LeaveManagement() {
        initComponents();
        applyLeave = new ApplyLeave();
        leaveSummary = new LeaveSummary();
        approveLeave = new ApproveLeave();
        DynamicPanel.setLayout(gridBaglayout);

        GridBagConstraints constraints = new GridBagConstraints();

        constraints.gridx = 0;
        constraints.gridy = 0;
        DynamicPanel.add(applyLeave, constraints);

        constraints.gridx = 0;
        constraints.gridy = 0;
        DynamicPanel.add(leaveSummary, constraints);

        constraints.gridx = 0;
        constraints.gridy = 0;
        DynamicPanel.add(approveLeave, constraints);

        applyLeave.setVisible(true);
        leaveSummary.setVisible(false);
        approveLeave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLeaveTitle = new javax.swing.JLabel();
        pnlApplyLeave = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlLeaveSummary = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlLeaveApproval = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leave Details");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frLeave"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setName("pnlLeave"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 0, 50));
        jPanel2.setName("pnlNavigation"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLeaveTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblLeaveTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblLeaveTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLeaveTitle.setText("LEAVE DETAILS");
        jPanel2.add(lblLeaveTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 30));

        pnlApplyLeave.setBackground(new java.awt.Color(64, 0, 33));
        pnlApplyLeave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlApplyLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlApplyLeave.setPreferredSize(new java.awt.Dimension(150, 41));
        pnlApplyLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlApplyLeaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlApplyLeaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlApplyLeaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlApplyLeaveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlApplyLeaveMouseReleased(evt);
            }
        });
        pnlApplyLeave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 97, 17));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-timer-20.png"))); // NOI18N
        jLabel4.setText("Apply Leave");
        pnlApplyLeave.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 41));

        jPanel2.add(pnlApplyLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 41));

        pnlLeaveSummary.setBackground(new java.awt.Color(64, 0, 33));
        pnlLeaveSummary.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLeaveSummary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLeaveSummary.setPreferredSize(new java.awt.Dimension(172, 41));
        pnlLeaveSummary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLeaveSummaryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLeaveSummaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLeaveSummaryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLeaveSummaryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlLeaveSummaryMouseReleased(evt);
            }
        });
        pnlLeaveSummary.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-details-20.png"))); // NOI18N
        jLabel2.setText("Leave Summary");
        pnlLeaveSummary.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 40));

        jPanel2.add(pnlLeaveSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 41));

        pnlLeaveApproval.setBackground(new java.awt.Color(64, 0, 33));
        pnlLeaveApproval.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLeaveApproval.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLeaveApproval.setPreferredSize(new java.awt.Dimension(170, 41));
        pnlLeaveApproval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLeaveApprovalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLeaveApprovalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLeaveApprovalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLeaveApprovalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlLeaveApprovalMouseReleased(evt);
            }
        });
        pnlLeaveApproval.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-ok-20.png"))); // NOI18N
        jLabel1.setText("Leave Approval");
        pnlLeaveApproval.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 40));

        jPanel2.add(pnlLeaveApproval, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 41));

        pnlExit.setBackground(new java.awt.Color(64, 0, 33));
        pnlExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExit.setPreferredSize(new java.awt.Dimension(220, 41));
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExitMouseReleased(evt);
            }
        });
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-exit-20.png"))); // NOI18N
        jLabel5.setText("Exit Module");
        jLabel5.setFocusable(false);
        pnlExit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 41));

        jPanel2.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 220, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));
        jPanel2.getAccessibleContext().setAccessibleName("pnlNavigation");

        DynamicPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 580, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
        jPanel1.getAccessibleContext().setAccessibleName("pnlLeave");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Apply Leave 
    private void pnlApplyLeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApplyLeaveMouseClicked
        // TODO add your handling code here:
        applyLeave.setVisible(true);
        leaveSummary.setVisible(false);
        approveLeave.setVisible(false);
    }//GEN-LAST:event_pnlApplyLeaveMouseClicked

    private void pnlLeaveSummaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveSummaryMouseClicked
        // TODO add your handling code here:
        leaveSummary.setVisible(true);
        applyLeave.setVisible(false);
        approveLeave.setVisible(false);
    }//GEN-LAST:event_pnlLeaveSummaryMouseClicked

    private void pnlLeaveApprovalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveApprovalMouseClicked
        // TODO add your handling code here:
        approveLeave.setVisible(true);
        leaveSummary.setVisible(false);
        applyLeave.setVisible(false);
    }//GEN-LAST:event_pnlLeaveApprovalMouseClicked

    private void pnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseClicked
        // TODO add your handling code here:
        StaffManagementHome staffHome = new StaffManagementHome();
        staffHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlExitMouseClicked

    private void pnlApplyLeaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApplyLeaveMouseEntered
        pnlApplyLeave.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_pnlApplyLeaveMouseEntered

    private void pnlApplyLeaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApplyLeaveMouseExited
        pnlApplyLeave.setBackground(new Color(64, 0, 33));
    }//GEN-LAST:event_pnlApplyLeaveMouseExited

    private void pnlApplyLeaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApplyLeaveMousePressed
        pnlApplyLeave.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_pnlApplyLeaveMousePressed

    private void pnlApplyLeaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApplyLeaveMouseReleased
        pnlApplyLeave.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_pnlApplyLeaveMouseReleased

    private void pnlLeaveSummaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveSummaryMouseEntered
        pnlLeaveSummary.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_pnlLeaveSummaryMouseEntered

    private void pnlLeaveSummaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveSummaryMouseExited
        pnlLeaveSummary.setBackground(new Color(64, 0, 33));
    }//GEN-LAST:event_pnlLeaveSummaryMouseExited

    private void pnlLeaveSummaryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveSummaryMousePressed
        pnlLeaveSummary.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_pnlLeaveSummaryMousePressed

    private void pnlLeaveSummaryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveSummaryMouseReleased
        pnlLeaveSummary.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_pnlLeaveSummaryMouseReleased

    private void pnlLeaveApprovalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveApprovalMouseEntered
        pnlLeaveApproval.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_pnlLeaveApprovalMouseEntered

    private void pnlLeaveApprovalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveApprovalMouseExited
        pnlLeaveApproval.setBackground(new Color(64, 0, 33));
    }//GEN-LAST:event_pnlLeaveApprovalMouseExited

    private void pnlLeaveApprovalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveApprovalMousePressed
        pnlLeaveApproval.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_pnlLeaveApprovalMousePressed

    private void pnlLeaveApprovalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveApprovalMouseReleased
        pnlLeaveApproval.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_pnlLeaveApprovalMouseReleased

    private void pnlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseEntered
        pnlExit.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_pnlExitMouseEntered

    private void pnlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseExited
        pnlExit.setBackground(new Color(64,0,33));
    }//GEN-LAST:event_pnlExitMouseExited

    private void pnlExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMousePressed
        pnlExit.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_pnlExitMousePressed

    private void pnlExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseReleased
        pnlExit.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_pnlExitMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaveManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLeaveTitle;
    private javax.swing.JPanel pnlApplyLeave;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlLeaveApproval;
    private javax.swing.JPanel pnlLeaveSummary;
    // End of variables declaration//GEN-END:variables
}
