/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui;

import com.sliit.itp.staff.ui.panel.ApplyLeave;
import com.sliit.itp.staff.ui.panel.ApproveLeave;
import com.sliit.itp.staff.ui.panel.LeaveSummary;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author user
 */
public class LeaveManagement extends javax.swing.JFrame {
    GridBagLayout gridBaglayout = new GridBagLayout();
    ApplyLeave applyLeave;
    LeaveSummary leaveSummary;
    ApproveLeave approveLeave;   
    /**
     * Creates new form LeaveManagement
     */
    public LeaveManagement() {
        initComponents();
        applyLeave = new ApplyLeave();
        leaveSummary = new LeaveSummary();
        approveLeave = new ApproveLeave();
        DynamicPanel.setLayout(gridBaglayout);
        
        GridBagConstraints constraints = new GridBagConstraints();
        
        constraints.gridx = 0;
        constraints.gridy = 0;
        DynamicPanel.add(applyLeave, constraints);
        
        constraints.gridx = 0;
        constraints.gridy = 0;
        DynamicPanel.add(leaveSummary, constraints);
        
        constraints.gridx = 0;
        constraints.gridy = 0;
        DynamicPanel.add(approveLeave, constraints);
        
        applyLeave.setVisible(true);
        leaveSummary.setVisible(false);
        approveLeave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLeaveTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlApproveLeaveReq = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leave Details");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frLeave"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setName("pnlLeave"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 0, 50));
        jPanel2.setName("pnlNavigation"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLeaveTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblLeaveTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblLeaveTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLeaveTitle.setText("LEAVE DETAILS");
        jPanel2.add(lblLeaveTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 30));

        jPanel3.setBackground(new java.awt.Color(64, 0, 33));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 41));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 97, 17));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-timer-20.png"))); // NOI18N
        jLabel4.setText("Apply Leave");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 41));

        jPanel4.setBackground(new java.awt.Color(64, 0, 33));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setPreferredSize(new java.awt.Dimension(172, 41));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-details-20.png"))); // NOI18N
        jLabel2.setText("Leave Summary");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 41));

        pnlApproveLeaveReq.setBackground(new java.awt.Color(64, 0, 33));
        pnlApproveLeaveReq.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlApproveLeaveReq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlApproveLeaveReq.setPreferredSize(new java.awt.Dimension(170, 41));
        pnlApproveLeaveReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlApproveLeaveReqMouseClicked(evt);
            }
        });
        pnlApproveLeaveReq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-ok-20.png"))); // NOI18N
        jLabel1.setText("Leave Approval");
        pnlApproveLeaveReq.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 40));

        jPanel2.add(pnlApproveLeaveReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 41));

        pnlExit.setBackground(new java.awt.Color(64, 0, 33));
        pnlExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExit.setPreferredSize(new java.awt.Dimension(220, 41));
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExitMouseClicked(evt);
            }
        });
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-exit-20.png"))); // NOI18N
        jLabel5.setText("Exit Module");
        jLabel5.setFocusable(false);
        pnlExit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 41));

        jPanel2.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 220, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));
        jPanel2.getAccessibleContext().setAccessibleName("pnlNavigation");

        DynamicPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 580, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
        jPanel1.getAccessibleContext().setAccessibleName("pnlLeave");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        //Apply Leave 
    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        applyLeave.setVisible(true);
        leaveSummary.setVisible(false);
        approveLeave.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        leaveSummary.setVisible(true);
        applyLeave.setVisible(false);
        approveLeave.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void pnlApproveLeaveReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApproveLeaveReqMouseClicked
        // TODO add your handling code here:
        approveLeave.setVisible(true);
        leaveSummary.setVisible(false);
        applyLeave.setVisible(false);
    }//GEN-LAST:event_pnlApproveLeaveReqMouseClicked

    private void pnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseClicked
        // TODO add your handling code here:
        StaffManagementHome staffHome = new StaffManagementHome();
        staffHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaveManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblLeaveTitle;
    private javax.swing.JPanel pnlApproveLeaveReq;
    private javax.swing.JPanel pnlExit;
    // End of variables declaration//GEN-END:variables
}
