/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui;

import com.sliit.itp.staff.ui.panel.CreatePayslip;
import com.sliit.itp.staff.ui.panel.PaymentReport;
import java.awt.BorderLayout;

/**
 *
 * @author immsf
 */
public class PaymentHandling extends javax.swing.JFrame {

    CreatePayslip payslip;
    PaymentReport paymentReport;
    
    /**
     * Creates new form CreatePayroll
     */
    public PaymentHandling() {
        initComponents();
        payslip = new CreatePayslip();
        paymentReport = new PaymentReport();
        pnlDynamic.add(payslip, BorderLayout.PAGE_START);
        payslip.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlPayslip = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlGenerateReport = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlDynamic = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payroll");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(99, 0, 50));
        jPanel6.setMaximumSize(new java.awt.Dimension(220, 600));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PAYMENT DETAILS");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 40));

        pnlPayslip.setBackground(new java.awt.Color(64, 0, 33));
        pnlPayslip.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPayslip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPayslip.setPreferredSize(new java.awt.Dimension(190, 41));
        pnlPayslip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPayslipMouseClicked(evt);
            }
        });
        pnlPayslip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 97, 17));
        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-purchase-order-20.png"))); // NOI18N
        jLabel8.setText("Create Payslip");
        pnlPayslip.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 41));

        jPanel6.add(pnlPayslip, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, -1));

        pnlGenerateReport.setBackground(new java.awt.Color(64, 0, 33));
        pnlGenerateReport.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlGenerateReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGenerateReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGenerateReportMouseClicked(evt);
            }
        });
        pnlGenerateReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-increase-20.png"))); // NOI18N
        jLabel2.setText("Generate Report");
        pnlGenerateReport.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 41));

        jPanel6.add(pnlGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, -1));

        pnlExit.setBackground(new java.awt.Color(64, 0, 33));
        pnlExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExit.setPreferredSize(new java.awt.Dimension(220, 41));
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExitMouseClicked(evt);
            }
        });
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-exit-20.png"))); // NOI18N
        jLabel9.setText("Exit Module");
        jLabel9.setFocusable(false);
        pnlExit.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 41));

        jPanel6.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 220, 40));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlDynamic.setBackground(new java.awt.Color(255, 255, 255));
        pnlDynamic.setMaximumSize(new java.awt.Dimension(580, 600));
        pnlDynamic.setMinimumSize(new java.awt.Dimension(580, 600));
        pnlDynamic.setLayout(new java.awt.BorderLayout());
        jPanel5.add(pnlDynamic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 580, 600));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlPayslipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPayslipMouseClicked
        // TODO add your handling code here:
        payslip.setVisible(true);
    }//GEN-LAST:event_pnlPayslipMouseClicked

    private void pnlGenerateReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGenerateReportMouseClicked
        pnlDynamic.add(paymentReport, BorderLayout.PAGE_START);
        payslip.setVisible(false);
        paymentReport.setVisible(true);
    }//GEN-LAST:event_pnlGenerateReportMouseClicked

    private void pnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseClicked
        // TODO add your handling code here:
        StaffManagementHome staffHome = new StaffManagementHome();
        staffHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentHandling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnlAddEmployee;
    private javax.swing.JPanel pnlAddEmployee1;
    private javax.swing.JPanel pnlDynamic;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlGenerateReport;
    private javax.swing.JPanel pnlPayslip;
    // End of variables declaration//GEN-END:variables
}
