/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui;

import com.sliit.itp.staff.ui.panel.HandleStaffShifts;
import com.sliit.itp.staff.ui.panel.ShiftReport;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author immsf
 */
public class ShiftHandling extends javax.swing.JFrame {

    HandleStaffShifts handleShifts;
    ShiftReport shiftReport;

    /**
     * Creates new form ShiftHandling
     */
    public ShiftHandling() {
        initComponents();
        handleShifts = new HandleStaffShifts();
        shiftReport = new ShiftReport();
        pnlDynamic.add(handleShifts, BorderLayout.PAGE_START);
        handleShifts.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlShifts = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlGenerateReport = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlDynamic = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shift Handling");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(99, 0, 50));
        jPanel6.setMaximumSize(new java.awt.Dimension(220, 600));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SHIFT HANDLING");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 40));

        pnlShifts.setBackground(new java.awt.Color(64, 0, 33));
        pnlShifts.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlShifts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlShifts.setPreferredSize(new java.awt.Dimension(190, 41));
        pnlShifts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShiftsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlShiftsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlShiftsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlShiftsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlShiftsMouseReleased(evt);
            }
        });
        pnlShifts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 97, 17));
        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-timer-20.png"))); // NOI18N
        jLabel8.setText("Handle Staff Shifts");
        pnlShifts.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 41));

        jPanel6.add(pnlShifts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, -1));

        pnlGenerateReport.setBackground(new java.awt.Color(64, 0, 33));
        pnlGenerateReport.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlGenerateReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGenerateReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGenerateReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGenerateReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGenerateReportMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlGenerateReportMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlGenerateReportMouseReleased(evt);
            }
        });
        pnlGenerateReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-increase-20.png"))); // NOI18N
        jLabel2.setText("Generate Report");
        pnlGenerateReport.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 41));

        jPanel6.add(pnlGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, -1));

        pnlExit.setBackground(new java.awt.Color(64, 0, 33));
        pnlExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExit.setPreferredSize(new java.awt.Dimension(220, 41));
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExitMouseReleased(evt);
            }
        });
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-exit-20.png"))); // NOI18N
        jLabel9.setText("Exit Module");
        jLabel9.setFocusable(false);
        pnlExit.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 162, 41));

        jPanel6.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 220, 40));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlDynamic.setBackground(new java.awt.Color(255, 255, 255));
        pnlDynamic.setMaximumSize(new java.awt.Dimension(580, 600));
        pnlDynamic.setMinimumSize(new java.awt.Dimension(580, 600));
        pnlDynamic.setLayout(new java.awt.BorderLayout());
        jPanel5.add(pnlDynamic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 580, 600));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlShiftsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShiftsMouseClicked
        shiftReport.setVisible(false);
        handleShifts.setVisible(true);
    }//GEN-LAST:event_pnlShiftsMouseClicked

    private void pnlGenerateReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGenerateReportMouseClicked
        pnlDynamic.add(shiftReport, BorderLayout.PAGE_START);
        handleShifts.setVisible(false);
        shiftReport.setVisible(true);
    }//GEN-LAST:event_pnlGenerateReportMouseClicked

    private void pnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseClicked
        // TODO add your handling code here:
        StaffManagementHome staffHome = new StaffManagementHome();
        staffHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlExitMouseClicked

    private void pnlShiftsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShiftsMouseEntered
        pnlShifts.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_pnlShiftsMouseEntered

    private void pnlShiftsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShiftsMouseExited
        pnlShifts.setBackground(new Color(64, 0, 33));
    }//GEN-LAST:event_pnlShiftsMouseExited

    private void pnlShiftsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShiftsMousePressed
        pnlShifts.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_pnlShiftsMousePressed

    private void pnlShiftsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShiftsMouseReleased
        pnlShifts.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_pnlShiftsMouseReleased

    private void pnlGenerateReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGenerateReportMouseEntered
        pnlGenerateReport.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_pnlGenerateReportMouseEntered

    private void pnlGenerateReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGenerateReportMouseExited
        pnlGenerateReport.setBackground(new Color(64, 0, 33));
    }//GEN-LAST:event_pnlGenerateReportMouseExited

    private void pnlGenerateReportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGenerateReportMousePressed
        pnlGenerateReport.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_pnlGenerateReportMousePressed

    private void pnlGenerateReportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGenerateReportMouseReleased
        pnlGenerateReport.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_pnlGenerateReportMouseReleased

    private void pnlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseEntered
        pnlExit.setBackground(new Color(152, 7, 81));
    }//GEN-LAST:event_pnlExitMouseEntered

    private void pnlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseExited
        pnlExit.setBackground(new Color(64, 0, 33));
    }//GEN-LAST:event_pnlExitMouseExited

    private void pnlExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMousePressed
        pnlExit.setBackground(new Color(81, 0, 41));
    }//GEN-LAST:event_pnlExitMousePressed

    private void pnlExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseReleased
        pnlExit.setBackground(new Color(142, 12, 78));
    }//GEN-LAST:event_pnlExitMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShiftHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShiftHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShiftHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShiftHandling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShiftHandling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnlDynamic;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlGenerateReport;
    private javax.swing.JPanel pnlShifts;
    // End of variables declaration//GEN-END:variables
}
