/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.itp.staff.ui;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class StaffManagementHome extends javax.swing.JFrame {

    /**
     * Creates new form StaffManagementHome
     */
    public StaffManagementHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlExit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlStaffDetails = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlPayroll = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlLeave = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlWorkShift = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlMarkAttendance = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Management Dashboard");
        setMaximumSize(new java.awt.Dimension(750, 540));
        setMinimumSize(new java.awt.Dimension(750, 540));
        setName("frHome"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(750, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(750, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 540));
        jPanel1.setName("pnlDashboard"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlExit.setBackground(new java.awt.Color(255, 255, 255));
        pnlExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExit.setName("pnlMarkAttendance"); // NOI18N
        pnlExit.setPreferredSize(new java.awt.Dimension(230, 200));
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExitMouseReleased(evt);
            }
        });
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel2.setText("EXIT SYSTEM");
        jLabel2.setName("lblMarkAttendance"); // NOI18N
        pnlExit.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlExit.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        pnlStaffDetails.setBackground(new java.awt.Color(255, 255, 255));
        pnlStaffDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlStaffDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlStaffDetails.setName("pnlStaffDetails"); // NOI18N
        pnlStaffDetails.setPreferredSize(new java.awt.Dimension(230, 200));
        pnlStaffDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlStaffDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlStaffDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlStaffDetailsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlStaffDetailsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlStaffDetailsMouseReleased(evt);
            }
        });
        pnlStaffDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/employee.png"))); // NOI18N
        jLabel9.setDisabledIcon(null);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStaffDetails.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel3.setText("STAFF DETAILS");
        jLabel3.setName("lblStaffDetails"); // NOI18N
        pnlStaffDetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jPanel1.add(pnlStaffDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        pnlPayroll.setBackground(new java.awt.Color(255, 255, 255));
        pnlPayroll.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPayroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPayroll.setName("pnlPayroll"); // NOI18N
        pnlPayroll.setPreferredSize(new java.awt.Dimension(230, 200));
        pnlPayroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPayrollMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPayrollMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPayrollMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlPayrollMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlPayrollMouseReleased(evt);
            }
        });
        pnlPayroll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel6.setText("PAYROLL");
        jLabel6.setName("lblPayroll"); // NOI18N
        pnlPayroll.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/money.png"))); // NOI18N
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPayroll.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(pnlPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        pnlLeave.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLeave.setName("pnlLeave"); // NOI18N
        pnlLeave.setPreferredSize(new java.awt.Dimension(230, 200));
        pnlLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLeaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLeaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLeaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLeaveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlLeaveMouseReleased(evt);
            }
        });
        pnlLeave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel4.setText("LEAVE DETAILS");
        jLabel4.setName("lblLeave"); // NOI18N
        pnlLeave.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/calendar.png"))); // NOI18N
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlLeave.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(pnlLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        pnlWorkShift.setBackground(new java.awt.Color(255, 255, 255));
        pnlWorkShift.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlWorkShift.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlWorkShift.setName("pnlShift"); // NOI18N
        pnlWorkShift.setPreferredSize(new java.awt.Dimension(230, 200));
        pnlWorkShift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlWorkShiftMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlWorkShiftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlWorkShiftMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlWorkShiftMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlWorkShiftMouseReleased(evt);
            }
        });
        pnlWorkShift.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel5.setText("WORK SHIFT");
        jLabel5.setName("lblShift"); // NOI18N
        pnlWorkShift.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clock.png"))); // NOI18N
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlWorkShift.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(pnlWorkShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        pnlMarkAttendance.setBackground(new java.awt.Color(255, 255, 255));
        pnlMarkAttendance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMarkAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMarkAttendance.setName("pnlMarkAttendance"); // NOI18N
        pnlMarkAttendance.setPreferredSize(new java.awt.Dimension(230, 200));
        pnlMarkAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMarkAttendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMarkAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMarkAttendanceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlMarkAttendanceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlMarkAttendanceMouseReleased(evt);
            }
        });
        pnlMarkAttendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel12.setText("MARK ATTENDANCE");
        jLabel12.setName("lblMarkAttendance"); // NOI18N
        pnlMarkAttendance.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/barcode-scanner.png"))); // NOI18N
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMarkAttendance.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(pnlMarkAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setText("STAFF MANAGEMENT SYSTEM");
        jLabel1.setName("lblStaffDetails"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 470, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Open Leave Details UI
    private void pnlLeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveMouseClicked
        LeaveManagement leaveManagement = new LeaveManagement();
        leaveManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlLeaveMouseClicked

    // Open Attendance UI
    private void pnlMarkAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMarkAttendanceMouseClicked
        AttendanceManagement attendance = new AttendanceManagement();
        attendance.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMarkAttendanceMouseClicked

    private void pnlStaffDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStaffDetailsMouseClicked
        StaffDetails staffDetails = new StaffDetails();
        staffDetails.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlStaffDetailsMouseClicked

    private void pnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to exit the System?", 
                "Exit Staff Management Dashboard",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_pnlExitMouseClicked

    private void pnlPayrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPayrollMouseClicked
        PaymentHandling payroll = new PaymentHandling();
        payroll.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlPayrollMouseClicked

    private void pnlWorkShiftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlWorkShiftMouseClicked
        ShiftHandling shiftHandling = new ShiftHandling();
        shiftHandling.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlWorkShiftMouseClicked

    private void pnlStaffDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStaffDetailsMousePressed
        pnlStaffDetails.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_pnlStaffDetailsMousePressed

    private void pnlStaffDetailsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStaffDetailsMouseReleased
        pnlStaffDetails.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlStaffDetailsMouseReleased

    private void pnlStaffDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStaffDetailsMouseEntered
        pnlStaffDetails.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_pnlStaffDetailsMouseEntered

    private void pnlStaffDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStaffDetailsMouseExited
        pnlStaffDetails.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlStaffDetailsMouseExited

    private void pnlMarkAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMarkAttendanceMouseEntered
        pnlMarkAttendance.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_pnlMarkAttendanceMouseEntered

    private void pnlMarkAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMarkAttendanceMouseExited
        pnlMarkAttendance.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlMarkAttendanceMouseExited

    private void pnlMarkAttendanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMarkAttendanceMousePressed
        pnlMarkAttendance.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_pnlMarkAttendanceMousePressed

    private void pnlMarkAttendanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMarkAttendanceMouseReleased
        pnlMarkAttendance.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlMarkAttendanceMouseReleased

    private void pnlLeaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveMouseEntered
        pnlLeave.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_pnlLeaveMouseEntered

    private void pnlLeaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveMouseExited
        pnlLeave.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlLeaveMouseExited

    private void pnlLeaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveMousePressed
        pnlLeave.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_pnlLeaveMousePressed

    private void pnlLeaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeaveMouseReleased
        pnlLeave.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlLeaveMouseReleased

    private void pnlPayrollMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPayrollMouseEntered
        pnlPayroll.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_pnlPayrollMouseEntered

    private void pnlPayrollMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPayrollMouseExited
        pnlPayroll.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlPayrollMouseExited

    private void pnlPayrollMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPayrollMousePressed
        pnlPayroll.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_pnlPayrollMousePressed

    private void pnlPayrollMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPayrollMouseReleased
        pnlPayroll.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlPayrollMouseReleased

    private void pnlWorkShiftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlWorkShiftMouseEntered
        pnlWorkShift.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_pnlWorkShiftMouseEntered

    private void pnlWorkShiftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlWorkShiftMouseExited
        pnlWorkShift.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlWorkShiftMouseExited

    private void pnlWorkShiftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlWorkShiftMousePressed
        pnlWorkShift.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_pnlWorkShiftMousePressed

    private void pnlWorkShiftMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlWorkShiftMouseReleased
        pnlWorkShift.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlWorkShiftMouseReleased

    private void pnlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseEntered
        pnlExit.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_pnlExitMouseEntered

    private void pnlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseExited
        pnlExit.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlExitMouseExited

    private void pnlExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMousePressed
        pnlExit.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_pnlExitMousePressed

    private void pnlExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseReleased
        pnlExit.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pnlExitMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffManagementHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffManagementHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffManagementHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffManagementHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffManagementHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlLeave;
    private javax.swing.JPanel pnlMarkAttendance;
    private javax.swing.JPanel pnlPayroll;
    private javax.swing.JPanel pnlStaffDetails;
    private javax.swing.JPanel pnlWorkShift;
    // End of variables declaration//GEN-END:variables
}
